### PR TITLE
Adds support for the completion handler for UICollectionViews

### PR DESCRIPTION
**Pull request by tberman**
Adds the completion handler for the UICollectionView extension. Also adds it to the protocol and the UITableView extension, but I wonder if it would be better to remove it from the SectionedViewType protocol instead?

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @tberman ,

Can you maybe explain some of the use cases for this API?

Maybe it would make more sense to expand AnimationConfiguration with this and rename it to something more descriptive, like `endedUpdates: () -> Void)?`.

This seems little confusing to me, because it both represents `self.endUpdates()` event and animation completed events.

I'm assuming you only wanted animation completed event and I'm not sure how this fits with `self.endUpdates()`.

**Comment by tberman** [comment]
@kzaher I actually don't care as much about the animation completing as I do about the underlying operations completing so that I can fetch more data as necessary and not get the two out of sync.

I am definitely not a big fan of this applying to UITableView, but only did it this way because performUpdates is part of the SectionedViewType protocol. I would actually prefer to remove that from the protocol, and remove it from the UITableView implementation.

What do you think?

**Comment by kzaher** [comment]
Hi @tberman ,

Data sources are in the view layer. The logic you are trying to implement is in the data layer. Try to take a look at paging inside RxExample app in the main repo. We'll try to also add other paging examples there.

**Comment by tberman** [comment]
@kzaher not sure if that is how the underlying UICollectionView stuff works. If you don't wait until after the collection has properly updated to see how many items have been loaded and how big they are, how can you check to see if you should load more or not?

**Pull request closed without merging**
