### PR TITLE
Fix iOS, tvOS Deployment target & Travis CI build fail

### PR DESCRIPTION
**Pull request by ElonPark**
- change iOS, tvOS Deployment target equal to SwiftPM, CocoaPods indicated version

```diff
- IPHONEOS_DEPLOYMENT_TARGET = 12.0;
+ IPHONEOS_DEPLOYMENT_TARGET = 9.0;
- TVOS_DEPLOYMENT_TARGET = 12.0;
+ TVOS_DEPLOYMENT_TARGET = 9.0;
```

- Also fix Travis CI build fail
  - `carthage update --platform tvOS && carthage build --no-skip-current --platform tvOS`

### CODE REVIEW

**Comment by iamszabo** [comment]
Is there any reason this cannot be merged to master? @freak4pc

**Comment by Unknoob** [comment]
Can we get this merged? Both version 5.0.0 and 5.0.1 are broken on carthage and this PR would fix it.

**Comment by freak4pc** [comment]
Sorry, I haven't been looking into RxDataSources enough lately :) 
It seems specifically the Carthage-related CI isn't building with this change. Could you fix it and I'll merge and cut a new release? Thanks.

https://travis-ci.org/github/RxSwiftCommunity/RxDataSources/jobs/770505930

@ElonPark @valerianb

**Comment by ElonPark** [comment]
@freak4pc i'll check it

**Comment by ElonPark** [comment]
Travis CI build fail is side effect of #392

**Comment by ElonPark** [comment]
close #402

**Pull request merged**
