### PR TITLE
Reduce computational complexity

### PR DESCRIPTION
**Pull request by shoheiyokoyama**
Hi.

I reduced computational complexity.

The computational complexity of calculation `count` is O(N) unless the collection guarantees random-access performance.
To check whether a collection is empty, you should use `isEmpty` property.
See Apple Document [here](https://developer.apple.com/documentation/swift/array/2949997-count) for details.

The `isEmpty` property is O(1) operation.

### CODE REVIEW

**Comment by sgtsquiggs** [comment]
Where you have !variable.isEmpty, you could also use variable.isNotEmpty. I'm not sure if there is any advantage to either method.

**Comment by shoheiyokoyama** [comment]
@sgtsquiggs 
Renaming `isEmpty` to `isNotEmpty` may improve readability, But I think that there isn't much advantage to creating properties.

**Comment by kzaher** [comment]
I doubt this will improve the performance, but the code is nicer, so I'll merge this.

**Comment by shoheiyokoyama** [comment]
@kzaher Thanks!!

**Pull request merged**
