### PR TITLE
Fix ReactiveX/RxSwift reference at Cartfile.resolved

### PR DESCRIPTION
**Pull request by RafaelPlantard**
Anyone can help here?
The `Cartfile.resolved` is point for a relative path, but when used with `carthage (bootstrap|update) --cache-builds` it will always build again the whole project and RxSwift too.
So, I changed for point to GitHub.
@RxSwiftCommunity/contributors

### CODE REVIEW

**Comment by mkko** [comment]
Great catch! Thank you for pointing this out. I don't think it ever was meant to use local version of RxSwift.

However, while updating this, we could update it to point 4.4.0 to get the latest. Would you mind doing it?

**Comment by ainopara** [comment]
To make CI builds successfully, changes here https://github.com/RxSwiftCommunity/RxDataSources/pull/278/commits/4a7a05f907a4ed54f409522dc16bccd71ff99fed need to be applied.

**Comment by RafaelPlantard** [comment]
Thank @ainopara

**Comment by RafaelPlantard** [comment]
@ainopara @mkko can help me as reviewers?

**Pull request merged**
