### PR TITLE
Reimplemented editing table view example 

### PR DESCRIPTION
**Pull request by sergdort**
To use pure transformation rather then mutate original datasource

### CODE REVIEW

**Comment by sergdort** [comment]
Hi, @kzaher  I facing strange issue.

Add and remove items works fine and when I move item within the same section, but when I move it from one section to another `UITableView` crashes

But the `ChangeSet` and result data in the `datasource` remains correct

**Comment by kzaher** [comment]
Hi @sergdort ,

I think I maybe understand what's happening and I might have a simple solution for this.

I'll try to implement it and test it when I find time.

**Comment by sergdort** [comment]
Ok, thanks 👍

**Comment by kzaher** [comment]
I think I've solved the issues you were experiencing :)

**Comment by sergdort** [comment]
I see you used `dispatch_async `. Was it something wrong with `UITableView` ? :)

**Comment by kzaher** [comment]
These were the problems:
First problem was that state was being kept in 3 distinct places:
* inside table view
* data source sections
* and inside `zip` operator

I've removed storing state inside that `zip` operator.

The second problem was that when you move row inside UITableView, the internal state changes, and then even it being fired to change the data in "original" data source. I've made state inside data source mirror that of internal state inside table view, and made sure with `dispatch_async` that any externally induced changes are recorded after that initial synchronous change of state on row moved inside the data source.

I'm not happy about using that `dispatch_async`, and I'm thinking how to make this conceptually cleaner.
One solution would be to change the order of DelegateProxy forwardDelegate method vs DelegateProxy observers. I'm thinking of changing that order for RxSwift 3.0. Can't change it now in 2.0 because that's a potentially hidden breaking change.

Probably more transparent solution would be to introduce `observeDelegateMessageSending` and `observeDelegateMessageSent`, or some similar naming, to better document the order of observing on `DelegateProxy`, and then then use `observeDelegateMessageSent` for `UITableView+Rx` extensions.

**Pull request merged**
