### PR TITLE
Adds editable tableView example

### PR DESCRIPTION
**Pull request by sergdort**
Hi, guys I've added editable tableView example setup if you don't mind 😀

### CODE REVIEW

**Comment by thonydam** [comment]
Hey @sergdort,

Thanks for this example. Do you know what would be the best way to have multiple SectionModelTypes in the same dataSource?

I have a Table view with different cells and would like to configureCell: method to configure them.

Thanks

**Comment by sergdort** [comment]
Hi, @thonydam 
Well, I think that your `SectionModelTypes` should be related somehow, because you will not be able to use `RxTableViewSectioned...DataSource `

Then in your `cellFactory`
```swift
dataSource.cellFactory = { (tableView, indexPath, model ) in
          if let someModel  = model as? SomeModel {
                  // configure and return cell
          }
          if let someOtherModel  = model as? SomeOtherModel {
                  // configure and return cell
          }
    }
```

Also there is a way to do this with associated `enum` 

In this case you will need to `switch` over it in the `cellFactory` and return configured cell

But I haven't tried this idea yet :)

**Comment by thonydam** [comment]
@sergdort,

Yeah the `RXTableViewSectionedDataSource` is compatible with only one model type. 

Checking the modelType in the `configureCell` is definitely the way to go. I will need to figure how to build a datasource with multiple `SectionModelTypes`

**Comment by icanzilb** [comment]
@thonydam having different models works fine for me, you can have a look at an example here: https://github.com/icanzilb/EventBlankApp/blob/bleeding-edge/EventBlank/EventBlank2-iOS/ViewControllers/SpeakersDetails/SpeakerDetailsViewModel.swift#L25

**Comment by kzaher** [comment]
Hi @sergdort ,

thnx :+1:

I'll merge this. 

It would also be great if we could have also an editing example that doesn't modify the data source data, but uses a more pure transformation using `scan` operator for rows.

Something like we have in RxExample app.

```swift
        let deleteUserCommand = tableView.rx_itemDeleted.map(TableViewEditingCommand.DeleteUser)
        let moveUserCommand = tableView.rx_itemMoved.map(TableViewEditingCommand.MoveUser)

        let initialState = TableViewEditingCommandsViewModel(favoriteUsers: [], users: [])

        let viewModel =  Observable.of(initialLoadCommand, deleteUserCommand, moveUserCommand)
            .merge()
            .scan(initialState) { $0.executeCommand($1) }
            .shareReplay(1)
``` 

Adding another example is ok, or modifying this one.

**Comment by sergdort** [comment]
Ha, @kzaher  that is very good point 👍

**Pull request merged**
