### PR TITLE
Make framework available to Carthage

### PR DESCRIPTION
**Pull request by coryoso**
Started making the framework available to carthage by sharing the framework scheme.
Carthage build currently fails as the framework target must execute cocoapods commands.
Creating a second framework target just for carthage does not seem right. 
Any suggestions?

### CODE REVIEW

**Comment by kzaher** [comment]
@coryoso ,

I didn't have any other solution then creating another scheme and target in `RxDataSources.xcodeproj` for Carthage. ¯\\\_(ツ)\_/¯ 

I don't have a problem with using that until we find some other solution for Carthage and merging PR. Simple and ugly trumps unknown solution :)

Thnx for helping out with Carthage support.

**Comment by coryoso** [comment]
@kzaher ,

So I looked into better options, but as of now I did not find anything better.
Only problem remaining is the need for the framework to import RxCocoa, which should not be bundled with RxDataSources.
Any Idea?

**Comment by kzaher** [comment]
Take a look at [Moya](https://github.com/Moya/Moya).

I believe that you should just include `Carthage/Checkouts` and not `Carthage/Build` directory. We should probably include that in `.gitignore` file. In that way only git references will be stored, and not binaries, although I believe you should reference those binaries from `Build` directory because they will be placed there after Carthage builds them.

That is my understanding.

**Comment by coryoso** [comment]
So i'm about done with the carthage integration, only step missing is tagging. Should I tag with version 0.2? (Also merging is missing, of course :))

**Comment by coryoso** [comment]
Also, I added support for tvOS (Same files, just a separat target)

**Pull request merged**
