### PR TITLE
[WIP] Detach diff algorithm from main module

### PR DESCRIPTION
**Pull request by muukii**
## TODO

- [x] Determine module name. => Differentiator
- [x] Determine functions each module.
- [x] Fix Tests.
- [x] Remove WIP commits when merge into master.
- [x] Tidy up Directories
- [ ] Fix podspec
  - [x] Update RxDataSources.podspec
  - [x] Add Differentiator.podspec
  - [ ] `pod trunk push Differentiator.podspec` ( @kzaher please push )

- [x] Bump up version 2.0.0 (Because, this PR has big changes)
- [x] Fix scripts/common.sh
- [ ] Update CHANGELOG.md
- [ ] Update README.md
- [ ] Test `carhtage build --no-skip-current`
- [ ] Test `pod lib lint`
- [x] Fix Travis

## Breaking changes

- Add `Differentiator` Module
- `DifferentiatorError` -> `Diff.Error`
- Remove Example by CocoaPods
- Remove `Differentiator-Test`, Using `Test`
- Remove xcworkspace, Pods/

#149 

## Memo

screen shot 2017-08-05 at 19 10 21

### CODE REVIEW

**Comment by muukii** [comment]
@dangthaison91
Hi, This PR will complete as soon as.
What do you think?

**Comment by kzaher** [comment]
Hi @muukii ,
I don't think that it's possible to review all of these changes in this way.

I'm assuming that what's partially causing problems for you and making this PR so huge is changing of the way dependencies are used.

It looks like you've commited RxSwift binaries to this repo. This is not optimal because:
* it's unrelated with any dependency resolution library, so there might be linker errors after compilation
* Swift isn't ABI stable so future Xcode versions will probably fail to compile this
* It greatly increases size the size of this repository when it's being cloned (this is one of the reasons why we never commit binaries inside the repositories)
* we ideally never want to distribute binaries since they represent a security hole (we can't guarantee what code is being shipped, somebody could inject malware inside this repo and we don't have any way of knowing what happened).

I've unfortunately needed to attach RxSwift.framework in RxSwift repo because combination of Carthage + Swift was unbearable and people were complaining a lot about compilation speed.

To fix the mentioned issues with inclusion of binaries inside this repo I'll need to unfortunately close this PR, delete the branch and make sure those binaries aren't referenced anywhere go we can gc the repository, sorry 😢 . 

I'll try to improve how we do dependencies in this repo and then we can continue with this 😢 .

**Comment by muukii** [comment]
Hi, @kzaher 
I have not commented RxSwift binaries. 🤔
I've removed `Pods/` directory.
Actually, This branch is lighter than currently 😎

And, I think that committing binaries is not optimal too.

Would you like to check this branch?

**Comment by muukii** [comment]
Hi, @kzaher 
I'm sorry 😱.
I did not notice that I committed the binary 😨.
I've removed committed binaries and rebased. (Pushed)
Actually, This branch is lighter than currently 😎

And, I think that committing binaries is not optimal too.

Would you like to check this branch?

**Comment by muukii** [comment]
@kzaher 
I've created again. https://github.com/RxSwiftCommunity/RxDataSources/pull/154
Please, check this. 🙏

**Pull request closed without merging**
