### PR TITLE
Fix build failure on New Build System (default on Xcode 10)

### PR DESCRIPTION
**Pull request by LeeroyDing**
Deleted reference to Rx.project as suggested in https://github.com/RxSwiftCommunity/RxDataSources/issues/237

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey Leeroy

We usually don't merge Beta-related changes to master until the beta is stabilized enough (e.g. pre-GM). 

Also, this fix must retain backward compatibility.

**Comment by LeeroyDing** [comment]
Hi @freak4pc thanks for the feedback. Should I leave the PR open and fix compatibility issues while we wait for Xcode 10 GM?

**Comment by freak4pc** [comment]
Hey Leeroy
Sure, I’d you fix compatibility you may leave it but Iran probably better to aim it at a new xcode10 branch.

As soon as you have this stabilized I’ll open a new branch and help out

**Comment by LeeroyDing** [comment]
That'd be amazing. I'm also waiting for Travis to create a Xcode 10 image so that we can run them on CI.

**Comment by freak4pc** [comment]
Oh you're right about that. That would make this very tricky - but, if you can create code that locally builds for you on Xcode 10 and preferably also on Xcode 9.4.1, I can test it locally as well and create a branch for it.

**Comment by rynecheow** [comment]
Xcode 10 GM Seed is released. Any plans to test and merge this PR yet?

**Comment by freak4pc** [comment]
This PR still doesn't retain backward compatibility. @LeeroyDing Could you make sure this properly build on Xcode 9.4 as well? 

Thanks.

**Comment by LeeroyDing** [comment]
I don't have time within a couple of days, I'll take a look next week and meanwhile any help is appreciated.

**Comment by LeeroyDing** [comment]
Looks like it has already been fixed on master :)

**Pull request closed without merging**
