### PR TITLE
tableView(_:canEditRowAtIndexPath:) conforms to the apple documentation

### LINKED ISSUE #39: tableView(_:canEditRowAtIndexPath:) returns true by default
The UITableView dataSource implementation of the method `tableView(_:canEditRowAtIndexPath:)` is returning true by default. 
This can cause unexpected behaviour when using RxDataSource, an example is the `Customization using table view delegate` in the Example app that shows the delete button when sliding the cell from the right to the left.

According with the [documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewDataSource_Protocol/#//apple_ref/occ/intfm/UITableViewDataSource/tableView:canEditRowAtIndexPath:) the default value should be:
>Return Value
>true if the row indicated by indexPath is editable; otherwise, false.

### PR DESCRIPTION
**Pull request by serluca**
This should fix #39

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @serluca ,

Thnx for reporting this. I'm not sure we would want this problem this way because it would require creation of entire new cell object for that check.

I think that a more performant way would be to create a new boolean property `canEditRowAtIndexPathExists: Bool` and use that in `respondsToSelector` to control does data source responds to that selector.

That would enable subclasses to check does some `canEditRowAtIndexPath` lambda exist, and in case it does, it would enable returning true from `canEditRowAtIndexPathExists` and using `canEditRowAtIndexPath` lambda.

**Comment by serluca** [comment]
Hi @kzaher 

I agree with it can be expensive doing this way, we can go with your solution.

**Comment by kzaher** [comment]
Hey, I've pushed the changes to master branch, but Delete button displays even though that selector isn't implemented. Hm...

**Comment by serluca** [comment]
Hi @kzaher 

As I can see from your commit aec86f0113e6b765675aea8b40600e0e327497f9 you are returning `true` if the datasource implements `canEditRowAtIndexPath`, `false` if not.
Indeed the delete button displays in the example 1, it doesn't in the example 4 and it also doesn't in the example 4 if you return `true`

**Comment by serluca** [comment]
HI @kzaher 

So, ignore my previous comment I was wrong. Your implementation is working, the problem is only when `dataSource.canEditRowAtIndexPath` is not defined.
I went deeply into your code and I maybe found a solution.

For some reason (I'm still not sure why) when `respondsToSelector` of `_TableViewSectionedDataSource` returns `false` for the selector `#selector(UITableViewDataSource.tableView(_:canEditRowAtIndexPath:))` the default implementation of  `canEditRowAtIndexPath` is true.

What I figured out is that, you actually don't need to check if the `_TableViewSectionedDataSource` responds to that selector, I was able to get it working removing the entire logic of `canEditRowAtIndexPathImplemented` and returning false for `func _rx_tableView(tableView: UITableView, canEditRowAtIndexPath indexPath: NSIndexPath) -> Bool`

Doing this, when `dataSource.canEditRowAtIndexPath` is defined it returns that value, false if is not.

I'll try to do a pull request

**Comment by kzaher** [comment]
Merged other PR.

**Pull request closed without merging**
